// Load the TSSC Jenkins Library
library identifier: 'tssc-jenkins-library@v0.13.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/rhtconsulting/tssc-jenkins-library.git'
])

// run the pipeline
pipelineMaven(
    configDir: 'cicd/tssc/',
    credentialIDsopsPGPKey: 'sops-pgp-private-key-jenkins-tssc-references',

    jenkinsWorkersImageRegesitryURI: 'quay.io',
    jenkinsWorkersImageRepositoryName: 'tssc',
    jenkinsWorkersImageTag: 'v0.13.0',
    jenkinsWorkersImagePullPolicy: 'Always',

    releaseBranchPatterns: ['main','release/*'],
    devBranchPatterns: ['^feature/.*$', '^PR-.*$', 'release/*'],

    updateTsscLibrary: true,
    tsscLibVersion: "0.13.0"
)
