// Load the TSSC Jenkins Library
library identifier: 'tssc-jenkins-library@feature/NAPSSPO-1033-pip-during-build',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/rhtconsulting/tssc-jenkins-library.git'
])

// run the pipeline
pipelineJava8(
    configDir: 'cicd/tssc/',
    credentialIDsopsPGPKey: 'sops-pgp-private-key-jenkins-tssc-references',

    jenkinsWorkersImageRegesitryURI: 'quay.io',
    jenkinsWorkersImageRepositoryName: 'tssc',
    jenkinsWorkersImageTag: 'edge',
    jenkinsWorkersImagePullPolicy: 'Always',

    tsscLibSourceUrl: "git+https://github.com/rhtconsulting/tssc-python-package.git@main"
)
